# Base Configuration for CoralScapes Segmentation
# This file contains only the essential configurable parameters

# Dataset Configuration
dataset:
  name: "CoralScapes"
  input_size: [128, 256]  # [height, width]
  num_classes: 40
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Model Configuration
model:
  name: "UNet"  # Options: UNet, DINOv3
  
  # UNet specific parameters
  unet:
    in_channels: 3
    out_channels: 40
    init_features: 64
  
  # DINOv3 specific parameters
  dinov3:
    pretrained_model_name: "facebook/dinov3-convnext-base-pretrain-lvd1689m"
    hidden_size: 384
    tokenW: 16
    tokenH: 8

# Training Configuration
training:
  num_epochs: 2000
  batch_size: 32
  learning_rate: 1e-3
  
  # Optimizer settings
  optimizer:
    name: "AdamW"
    lr: 1e-3
    weight_decay: 1e-4
    betas: [0.9, 0.999]
  
  # Learning rate scheduler
  scheduler:
    name: "CosineAnnealingWarmRestarts"
    T_0: 100
    T_mult: 2
    eta_min: 1e-6
  
  # Loss function
  loss:
    name: "cross_entropy+dice"
    params:
      dice_weight: 0.5
      focal_alpha: 1.0
      focal_gamma: 2.0

# Data Augmentation
augmentation:
  train:
    enable: true
    random_crop:
      enable: true
      size: [128, 128]
    random_horizontal_flip:
      enable: true
      probability: 0.5
    random_rotation:
      enable: true
      degrees: 45
    random_affine:
      enable: true
      probability: 0.5
      degrees: 20
      translate: [0.05, 0.05]